const state={playerId:Number(localStorage.getItem('tutien_player_id')||0),profile:null,config:null,busy:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function api(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await res.json().catch(()=>({}));if(!res.ok||data.success===false)throw new Error(data.error||'Thiên Cơ không phản hồi.');return data}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function activityName(v){return({idle:'Tĩnh tọa',spirit_cultivation:'Linh Tu',combat:'Chiến Đạo'})[v]||v}
function fmt(n){return Number(n||0).toLocaleString('vi-VN')}
async function loadConfig(){state.config=await api('/api/config')}
async function openGame(data){state.profile=data;state.playerId=Number(data.player.id);localStorage.setItem('tutien_player_id',state.playerId);$('#gate').classList.add('hidden');$('#game').classList.remove('hidden');render()}
function render(){const d=state.profile,p=d.player;$('#playerName').textContent=p.name;$('#activityBadge').textContent=activityName(p.current_activity);$('#realm').textContent=`${p.realm_name} · Tầng ${p.main_layer}`;$('#power').textContent=fmt(p.power);$('#stones').textContent=fmt(p.spirit_stones);$('#hp').textContent=`${fmt(p.current_hp)} / ${fmt(p.max_hp)}`;$('#expText').textContent=`${fmt(p.main_exp)} / ${fmt(p.exp_required)}`;$('#rateText').textContent=`${p.exp_percent}%`;$('#expBar').style.width=`${p.exp_percent}%`;$('#bodyExp').textContent=fmt(p.body_exp);$('#soulExp').textContent=fmt(p.soul_exp);$('#breakBtn').disabled=!p.can_breakthrough;const map=state.config.maps.find(x=>x.id===p.map_id);const mon=state.config.monsters.find(x=>x.id===p.monster_id);$('#mapName').textContent=map?.name||'Chưa chọn';$('#monsterName').textContent=mon?.name||'Chưa gặp yêu thú';const mh=p.monster_max_hp?Math.max(0,p.monster_hp/p.monster_max_hp*100):0;$('#monsterBar').style.width=`${mh}%`;$('#monsterHp').textContent=`${fmt(p.monster_hp)} / ${fmt(p.monster_max_hp)}`;$('#record').textContent=`${fmt(p.wins)} thắng · ${fmt(p.losses)} bại`;renderInventory(d.inventory);renderLogs(d.logs);renderMaps(p.unlocked_maps||[])}
function renderInventory(items){$('#inventoryGrid').innerHTML=items.length?items.map(x=>`<article class="item"><h4>${x.item_name}</h4><div class="qty">${fmt(x.quantity)}</div><small>${x.item_type}</small>${x.item_id==='hoi_khi_dan'?`<p>${x.metadata?.effect||''}</p><button onclick="useItem('${x.item_id}')">Sử dụng</button>`:''}</article>`).join(''):'<article class="card">Túi Càn Khôn trống.</article>'}
function renderLogs(logs){$('#logList').innerHTML=logs.length?logs.map(x=>`<div class="log"><b>[${x.category}]</b> ${x.message}<small>${new Date(x.created_at).toLocaleString('vi-VN')}</small></div>`).join(''):'Chưa có đạo hành được ghi nhận.'}
function renderMaps(unlocked){const ids=new Set(unlocked.map(x=>x.id));$('#mapList').innerHTML=state.config.maps.map(m=>`<div class="map-option ${ids.has(m.id)?'':'locked'}"><div><b>${m.name}</b><small style="display:block">Yêu cầu: ${state.config.realms[m.realmRequired].name} tầng ${m.layerRequired}</small></div><button ${ids.has(m.id)?`onclick="selectMap(${m.id})"`:'disabled'}>Chọn</button></div>`).join('')}
async function refresh(){if(!state.playerId||state.busy)return;state.busy=true;try{openGame(await api(`/api/game/${state.playerId}/tick`,{method:'POST'}))}catch(e){toast(e.message)}finally{state.busy=false}}
async function changeActivity(activity){try{openGame(await api(`/api/game/${state.playerId}/activity`,{method:'POST',body:JSON.stringify({activity})}));toast(`Đã chuyển sang ${activityName(activity)}.`)}catch(e){toast(e.message)}}
async function selectMap(mapId){try{openGame(await api(`/api/game/${state.playerId}/select-map`,{method:'POST',body:JSON.stringify({mapId})}));$('#modal').classList.add('hidden')}catch(e){toast(e.message)}}
async function useItem(itemId){try{openGame(await api(`/api/game/${state.playerId}/use-item`,{method:'POST',body:JSON.stringify({itemId})}))}catch(e){toast(e.message)}}
window.selectMap=selectMap;window.useItem=useItem;
$('#createBtn').onclick=async()=>{try{openGame(await api('/api/player',{method:'POST',body:JSON.stringify({name:$('#nameInput').value})}))}catch(e){$('#gateMsg').textContent=e.message}};
$('#loadBtn').onclick=async()=>{try{openGame(await api(`/api/player/by-name/${encodeURIComponent($('#nameInput').value.trim())}`))}catch(e){$('#gateMsg').textContent=e.message}};
$('#breakBtn').onclick=async()=>{try{openGame(await api(`/api/game/${state.playerId}/breakthrough`,{method:'POST'}))}catch(e){toast(e.message)}};
$$('[data-action]').forEach(b=>b.onclick=()=>changeActivity(b.dataset.action));
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.tab-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#mapBtn').onclick=()=>$('#modal').classList.remove('hidden');$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('tutien_theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('tutien_theme')==='dark')document.body.classList.add('dark');
(async()=>{try{await loadConfig();if(state.playerId)openGame(await api(`/api/player/${state.playerId}`));setInterval(refresh,2000)}catch(e){toast(e.message)}})();
