-- ============================================================
-- NHÂN GIỚI ĐẠO TẠNG - ONE-SHOT DATABASE SCHEMA
-- MySQL 8.0+
-- Chạy toàn bộ file một lần.
-- ============================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE IF NOT EXISTS tutien_idle CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tutien_idle;

DROP TABLE IF EXISTS player_logs,player_effects,player_encounter_cooldowns,player_encounters,player_herb_plots,player_cave,player_alchemy_jobs,player_alchemist,player_monster_statistics,player_combat_state,player_map_unlocks,player_skill_loadout,player_skills,player_equipment,player_inventory,player_activity,player_attributes,player_cultivation,players,accounts;

CREATE TABLE accounts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) NOT NULL,password_hash VARCHAR(255) NOT NULL,status ENUM('active','locked','banned') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,last_login_at DATETIME NULL,UNIQUE KEY uq_accounts_username(username)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE players(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,account_id BIGINT UNSIGNED NULL,name VARCHAR(50) NOT NULL,world_id VARCHAR(100) NOT NULL DEFAULT 'nhan_gioi',spiritual_root_id VARCHAR(100) NOT NULL DEFAULT 'linh_can_pham',spirit_stones BIGINT UNSIGNED NOT NULL DEFAULT 0,current_hp BIGINT UNSIGNED NOT NULL DEFAULT 100,current_mp BIGINT UNSIGNED NOT NULL DEFAULT 0,current_activity VARCHAR(50) NOT NULL DEFAULT 'idle',current_map_id VARCHAR(100) NULL,age_years INT UNSIGNED NOT NULL DEFAULT 16,lifespan_years INT UNSIGNED NOT NULL DEFAULT 80,last_action_at DATETIME NULL,last_tick_at DATETIME NULL,last_online_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_players_name(name),KEY idx_players_account_id(account_id),CONSTRAINT fk_players_account FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_cultivation(player_id BIGINT UNSIGNED PRIMARY KEY,main_realm_id VARCHAR(100) NOT NULL,main_layer SMALLINT UNSIGNED NOT NULL DEFAULT 1,main_exp BIGINT UNSIGNED NOT NULL DEFAULT 0,body_realm_id VARCHAR(100) NOT NULL,body_layer SMALLINT UNSIGNED NOT NULL DEFAULT 1,body_exp BIGINT UNSIGNED NOT NULL DEFAULT 0,soul_realm_id VARCHAR(100) NOT NULL,soul_layer SMALLINT UNSIGNED NOT NULL DEFAULT 1,soul_exp BIGINT UNSIGNED NOT NULL DEFAULT 0,main_breakthrough_failures INT UNSIGNED NOT NULL DEFAULT 0,body_breakthrough_failures INT UNSIGNED NOT NULL DEFAULT 0,soul_breakthrough_failures INT UNSIGNED NOT NULL DEFAULT 0,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_cultivation_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_attributes(player_id BIGINT UNSIGNED PRIMARY KEY,bonus_hp BIGINT NOT NULL DEFAULT 0,bonus_mp BIGINT NOT NULL DEFAULT 0,bonus_attack BIGINT NOT NULL DEFAULT 0,bonus_defense BIGINT NOT NULL DEFAULT 0,bonus_speed BIGINT NOT NULL DEFAULT 0,bonus_crit_rate DECIMAL(10,4) NOT NULL DEFAULT 0,bonus_crit_damage DECIMAL(10,4) NOT NULL DEFAULT 0,bonus_dodge_rate DECIMAL(10,4) NOT NULL DEFAULT 0,free_attribute_points BIGINT UNSIGNED NOT NULL DEFAULT 0,CONSTRAINT fk_attributes_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_activity(player_id BIGINT UNSIGNED PRIMARY KEY,activity_type ENUM('idle','cultivation','combat','alchemy','planting','encounter') NOT NULL DEFAULT 'idle',target_id VARCHAR(100) NULL,started_at DATETIME NULL,finish_at DATETIME NULL,last_processed_at DATETIME NULL,activity_data JSON NULL,CONSTRAINT fk_activity_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_inventory(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,player_id BIGINT UNSIGNED NOT NULL,item_id VARCHAR(100) NOT NULL,quantity BIGINT UNSIGNED NOT NULL DEFAULT 1,bind_type ENUM('none','bound') NOT NULL DEFAULT 'none',slot_index INT UNSIGNED NULL,metadata JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_inventory_player(player_id),KEY idx_inventory_item(item_id),CONSTRAINT fk_inventory_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_equipment(player_id BIGINT UNSIGNED NOT NULL,equipment_slot VARCHAR(50) NOT NULL,inventory_item_id BIGINT UNSIGNED NOT NULL,equipped_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(player_id,equipment_slot),UNIQUE KEY uq_equipped_item(inventory_item_id),CONSTRAINT fk_equipment_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,CONSTRAINT fk_equipment_inventory FOREIGN KEY(inventory_item_id) REFERENCES player_inventory(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_skills(player_id BIGINT UNSIGNED NOT NULL,skill_id VARCHAR(100) NOT NULL,skill_level INT UNSIGNED NOT NULL DEFAULT 1,skill_exp BIGINT UNSIGNED NOT NULL DEFAULT 0,learned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(player_id,skill_id),CONSTRAINT fk_skills_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_skill_loadout(player_id BIGINT UNSIGNED NOT NULL,loadout_type ENUM('cultivation','combat','passive') NOT NULL,slot_index INT UNSIGNED NOT NULL,skill_id VARCHAR(100) NOT NULL,equipped_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(player_id,loadout_type,slot_index),UNIQUE KEY uq_player_skill(player_id,skill_id),CONSTRAINT fk_loadout_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_map_unlocks(player_id BIGINT UNSIGNED NOT NULL,map_id VARCHAR(100) NOT NULL,unlocked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(player_id,map_id),CONSTRAINT fk_map_unlock_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_combat_state(player_id BIGINT UNSIGNED PRIMARY KEY,map_id VARCHAR(100) NULL,monster_id VARCHAR(100) NULL,monster_current_hp BIGINT UNSIGNED NOT NULL DEFAULT 0,player_current_hp BIGINT UNSIGNED NOT NULL DEFAULT 0,combat_round BIGINT UNSIGNED NOT NULL DEFAULT 0,auto_combat_enabled BOOLEAN NOT NULL DEFAULT FALSE,combat_started_at DATETIME NULL,last_combat_tick_at DATETIME NULL,CONSTRAINT fk_combat_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_monster_statistics(player_id BIGINT UNSIGNED NOT NULL,monster_id VARCHAR(100) NOT NULL,kill_count BIGINT UNSIGNED NOT NULL DEFAULT 0,death_count BIGINT UNSIGNED NOT NULL DEFAULT 0,first_kill_at DATETIME NULL,last_kill_at DATETIME NULL,PRIMARY KEY(player_id,monster_id),CONSTRAINT fk_monster_stats_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_alchemist(player_id BIGINT UNSIGNED PRIMARY KEY,alchemist_rank_id VARCHAR(100) NOT NULL DEFAULT 'dan_su_nhat_pham',alchemist_level INT UNSIGNED NOT NULL DEFAULT 1,alchemist_exp BIGINT UNSIGNED NOT NULL DEFAULT 0,successful_crafts BIGINT UNSIGNED NOT NULL DEFAULT 0,failed_crafts BIGINT UNSIGNED NOT NULL DEFAULT 0,CONSTRAINT fk_alchemist_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_alchemy_jobs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,player_id BIGINT UNSIGNED NOT NULL,recipe_id VARCHAR(100) NOT NULL,quantity INT UNSIGNED NOT NULL DEFAULT 1,status ENUM('processing','completed','claimed','failed','cancelled') NOT NULL DEFAULT 'processing',success_rate DECIMAL(10,4) NOT NULL DEFAULT 0,started_at DATETIME NOT NULL,finish_at DATETIME NOT NULL,claimed_at DATETIME NULL,result_data JSON NULL,KEY idx_alchemy_player_status(player_id,status),CONSTRAINT fk_alchemy_jobs_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_cave(player_id BIGINT UNSIGNED PRIMARY KEY,cave_level INT UNSIGNED NOT NULL DEFAULT 1,spiritual_energy_level INT UNSIGNED NOT NULL DEFAULT 1,herb_plot_count INT UNSIGNED NOT NULL DEFAULT 3,storage_level INT UNSIGNED NOT NULL DEFAULT 1,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_cave_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_herb_plots(player_id BIGINT UNSIGNED NOT NULL,plot_index INT UNSIGNED NOT NULL,herb_id VARCHAR(100) NULL,planted_at DATETIME NULL,harvest_at DATETIME NULL,status ENUM('empty','growing','ready') NOT NULL DEFAULT 'empty',PRIMARY KEY(player_id,plot_index),CONSTRAINT fk_herb_plots_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_encounters(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,player_id BIGINT UNSIGNED NOT NULL,encounter_id VARCHAR(100) NOT NULL,status ENUM('pending','resolved','expired','ignored') NOT NULL DEFAULT 'pending',selected_choice_id VARCHAR(100) NULL,triggered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at DATETIME NULL,expires_at DATETIME NULL,reward_data JSON NULL,KEY idx_encounters_player_status(player_id,status),CONSTRAINT fk_encounters_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_encounter_cooldowns(player_id BIGINT UNSIGNED NOT NULL,encounter_id VARCHAR(100) NOT NULL,available_at DATETIME NOT NULL,PRIMARY KEY(player_id,encounter_id),CONSTRAINT fk_encounter_cd_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_effects(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,player_id BIGINT UNSIGNED NOT NULL,effect_id VARCHAR(100) NOT NULL,source_type VARCHAR(50) NOT NULL,source_id VARCHAR(100) NULL,stack_count INT UNSIGNED NOT NULL DEFAULT 1,started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NULL,effect_data JSON NULL,KEY idx_effects_player_expires(player_id,expires_at),CONSTRAINT fk_effects_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,player_id BIGINT UNSIGNED NOT NULL,category VARCHAR(50) NOT NULL,action VARCHAR(100) NOT NULL,title VARCHAR(255) NOT NULL,message TEXT NOT NULL,detail_data JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_logs_recent(player_id,created_at),KEY idx_logs_category(player_id,category,created_at),CONSTRAINT fk_logs_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
SELECT 'NHAN_GIOI_SCHEMA_READY' AS status;
