USE tutien_idle;

ALTER TABLE player_cultivation_arts
  ADD COLUMN IF NOT EXISTS proficiency BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER art_exp,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER learned_at;

CREATE TABLE IF NOT EXISTS player_art_resources (
  player_id BIGINT UNSIGNED NOT NULL,
  spirit_qi BIGINT UNSIGNED NOT NULL DEFAULT 0,
  battle_intent BIGINT UNSIGNED NOT NULL DEFAULT 0,
  blood_qi BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cultivation_essence BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  CONSTRAINT fk_art_resources_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO player_art_resources(player_id)
SELECT id FROM players
ON DUPLICATE KEY UPDATE player_id=VALUES(player_id);
