CREATE TABLE IF NOT EXISTS players (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  world_id VARCHAR(32) NOT NULL DEFAULT 'nhan_gioi',
  spiritual_root VARCHAR(64) NOT NULL DEFAULT 'ngu_hanh_tap_linh_can',
  spirit_stones BIGINT NOT NULL DEFAULT 100,
  current_hp BIGINT NOT NULL DEFAULT 100,
  current_mp BIGINT NOT NULL DEFAULT 50,
  current_activity ENUM('idle','spirit_cultivation','combat')
    NOT NULL DEFAULT 'idle',
  last_tick_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_players_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_cultivation (
  player_id BIGINT UNSIGNED PRIMARY KEY,
  main_realm_index INT NOT NULL DEFAULT 0,
  main_layer INT NOT NULL DEFAULT 1,
  main_exp BIGINT NOT NULL DEFAULT 0,
  body_realm_index INT NOT NULL DEFAULT 0,
  body_layer INT NOT NULL DEFAULT 1,
  body_exp BIGINT NOT NULL DEFAULT 0,
  soul_realm_index INT NOT NULL DEFAULT 0,
  soul_layer INT NOT NULL DEFAULT 1,
  soul_exp BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_attributes (
  player_id BIGINT UNSIGNED PRIMARY KEY,

  max_hp BIGINT NOT NULL DEFAULT 100,
  max_mp BIGINT NOT NULL DEFAULT 50,
  attack_value BIGINT NOT NULL DEFAULT 12,
  defense_value BIGINT NOT NULL DEFAULT 5,

  accuracy BIGINT NOT NULL DEFAULT 100,
  dodge_rate DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  crit_rate DECIMAL(7,4) NOT NULL DEFAULT 0.0500,
  crit_damage DECIMAL(7,4) NOT NULL DEFAULT 1.5000,
  speed_value BIGINT NOT NULL DEFAULT 10,
  armor_penetration BIGINT NOT NULL DEFAULT 0,
  crit_resistance DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  life_steal DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  hp_regen DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
  mp_regen DECIMAL(12,4) NOT NULL DEFAULT 2.0000,

  cultivation_rate DECIMAL(10,4) NOT NULL DEFAULT 2.0000,

  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_combat_state (
  player_id BIGINT UNSIGNED PRIMARY KEY,
  map_id INT NOT NULL DEFAULT 1,
  monster_id INT NULL,
  monster_hp BIGINT NOT NULL DEFAULT 0,
  monster_max_hp BIGINT NOT NULL DEFAULT 0,
  wins BIGINT NOT NULL DEFAULT 0,
  losses BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_inventory (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player_id BIGINT UNSIGNED NOT NULL,
  slot_index INT UNSIGNED NULL,
  item_id VARCHAR(64) NOT NULL,
  item_name VARCHAR(128) NOT NULL,
  item_type VARCHAR(32) NOT NULL,
  quantity BIGINT NOT NULL DEFAULT 0,
  metadata JSON NULL,
  UNIQUE KEY uq_inventory_slot (player_id, slot_index),
  KEY ix_inventory_item (player_id, item_id),
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player_id BIGINT UNSIGNED NOT NULL,
  category VARCHAR(32) NOT NULL,
  message VARCHAR(500) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_player_logs (player_id, id),
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
