// ============================================
// CONFIG - ELEMENT SKILL SETS
// Mỗi linh căn gồm: Luyện công / Vũ kỹ / Thần thông
// ============================================

const ELEMENT_SKILL_SETS = [
    {
        element: 'kim',
        name: 'Kim',
        cultivation: {
            id: 'thien_tinh_bat_huu_kinh',
            name: 'Thiên Tinh Bất Hủ Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'kim',
            desc: 'Dẫn kim tinh chi lực ngưng tụ trong kinh mạch, tạo nên cốt cách như thép.',
            tags: ['defense', 'body', 'metal_power'],
        },
        martial: {
            id: 'bach_ho_sat_phong_trao',
            name: 'Bạch Hổ Sát Phong Trảo',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'kim',
            desc: 'Móng vuốt sắc như bảo kiếm, mỗi đòn đều xé rách không khí, để lại vết cắt không gian.',
            tags: ['single_target', 'armor_break', 'slash'],
        },
        divine: {
            id: 'van_kiem_quy_tong',
            name: 'Vạn Kiếm Quy Tông',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'kim',
            desc: 'Hóa thân thành cơn mưa kiếm, vạn kiếm cùng lúc xuất phát từ cơ thể, tấn công toàn bộ kẻ địch trong phạm vi.',
            tags: ['aoe', 'sword_rain', 'multi_hit'],
        },
    },
    {
        element: 'moc',
        name: 'Mộc',
        cultivation: {
            id: 'truong_sinh_thanh_moc_quyet',
            name: 'Trường Sinh Thanh Mộc Quyết',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'moc',
            desc: 'Hấp thụ sinh khí thiên địa, chuyển hóa thành nguyên lực Mộc, giúp vết thương mau lành.',
            tags: ['regen', 'life_force', 'sustain'],
        },
        martial: {
            id: 'van_moc_tranh_phong',
            name: 'Vạn Mộc Tranh Phong',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'moc',
            desc: 'Điều khiển cành cây, dây leo từ mặt đất mọc lên, quấn chặt và đâm xuyên kẻ địch.',
            tags: ['control', 'bind', 'pierce'],
        },
        divine: {
            id: 'moc_gioi_linh_vuc',
            name: 'Mộc Giới Lĩnh Vực',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'moc',
            desc: 'Tạo ra một khu rừng thu nhỏ xung quanh, trong đó bản thân có thể ẩn thân, hồi phục và khống chế mọi sinh trưởng.',
            tags: ['domain', 'stealth', 'regen', 'control'],
        },
    },
    {
        element: 'thuy',
        name: 'Thủy',
        cultivation: {
            id: 'nhuoc_thuy_chan_nguyen_quyet',
            name: 'Nhược Thủy Chân Nguyên Quyết',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'thuy',
            desc: 'Luyện khí thành Thủy, mềm mại nhưng áp lực cực lớn, có thể xuyên thấu mọi phòng ngự.',
            tags: ['penetration', 'pressure', 'flexible_power'],
        },
        martial: {
            id: 'thuong_lang_ba_quyen',
            name: 'Thương Lang Bá Quyền',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'thuy',
            desc: 'Quyền pháp mềm dẻo như sóng biển, đòn đánh như thủy triều dồn dập, tầng tầng lớp lớp áp lực.',
            tags: ['combo', 'pressure', 'multi_wave'],
        },
        divine: {
            id: 'huyen_minh_bang_phong_chuong',
            name: 'Huyền Minh Băng Phong Chưởng',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'thuy',
            desc: 'Tích tụ hàn khí cực hạn, một chưởng đánh ra đóng băng tất cả máu huyết và nguyên lực đối thủ.',
            tags: ['freeze', 'disable', 'cold'],
        },
    },
    {
        element: 'hoa',
        name: 'Hỏa',
        cultivation: {
            id: 'phuong_hoang_luyen_nguyen_kinh',
            name: 'Phượng Hoàng Luyện Nguyên Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'hoa',
            desc: 'Lấy lửa luyện hóa tạp chất trong cơ thể, khiến nội nguyên càng lúc càng thuần khiết và bá đạo.',
            tags: ['purify', 'power_growth', 'fire_core'],
        },
        martial: {
            id: 'ly_hoa_chuong',
            name: 'Ly Hỏa Chưởng',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'hoa',
            desc: 'Chưởng pháp như dung nham, nơi bàn tay chạm tới đều bùng cháy, thiêu đốt cả nguyên thần kẻ địch.',
            tags: ['burn', 'soul_burn', 'melee'],
        },
        divine: {
            id: 'hong_lien_nghiep_hoa',
            name: 'Hồng Liên Nghiệp Hỏa',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'hoa',
            desc: 'Triệu hồi ngọn lửa màu đỏ thẫm, chuyên đốt cháy nghiệp chướng và linh hồn, không thể dập tắt bằng nước thường.',
            tags: ['dot', 'soul_burn', 'purge'],
        },
    },
    {
        element: 'tho',
        name: 'Thổ',
        cultivation: {
            id: 'hau_tho_bat_dong_kinh',
            name: 'Hậu Thổ Bất Động Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'tho',
            desc: 'Nội lực trầm ổn như núi, gia tăng trọng lượng và sức chịu đựng cơ thể.',
            tags: ['defense', 'stability', 'endurance'],
        },
        martial: {
            id: 'hoang_long_tran_nhac_quyen',
            name: 'Hoàng Long Trấn Nhạc Quyền',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'tho',
            desc: 'Mượn lực địa mạch, mỗi cú đấm mang sức nặng của ngọn núi, khiến địch phải gánh chịu trọng áp.',
            tags: ['heavy_hit', 'gravity', 'stun'],
        },
        divine: {
            id: 'can_khon_dia_tu',
            name: 'Càn Khôn Địa Từ',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'tho',
            desc: 'Thay đổi lực hấp dẫn cục bộ, tạo ra vùng trùng lực hoặc phản lực, nhốt địch trong lòng đất.',
            tags: ['domain', 'gravity', 'control'],
        },
    },
    {
        element: 'quang',
        name: 'Quang',
        cultivation: {
            id: 'dai_nhat_nhu_lai_chan_kinh',
            name: 'Đại Nhật Như Lai Chân Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'quang',
            desc: 'Nguyên lực thuần khiết như ánh nắng ban trưa, có tác dụng trừ tà và thanh tẩy độc tố.',
            tags: ['cleanse', 'anti_dark', 'purify'],
        },
        martial: {
            id: 'bach_hong_quyen',
            name: 'Bạch Hồng Quyền',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'quang',
            desc: 'Quyền pháp rực rỡ, tạo ra chùm sáng nóng chảy xuyên thủng mọi phòng ngự của bóng tối.',
            tags: ['pierce', 'anti_dark', 'light_burst'],
        },
        divine: {
            id: 'quang_minh_linh_vuc',
            name: 'Quang Minh Lĩnh Vực',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'quang',
            desc: 'Phạm vi chiếu sáng xung quanh hóa thành thánh vực, khiến kẻ địch bị bỏng mắt, giảm tốc độ và không thể ẩn thân.',
            tags: ['domain', 'reveal', 'slow', 'blind'],
        },
    },
    {
        element: 'am',
        name: 'Ám',
        cultivation: {
            id: 'thai_am_cuu_u_kinh',
            name: 'Thái Âm Cửu U Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'am',
            desc: 'Nguyên lực u ám, trầm lắng, có tính hút và nuốt chửng các loại năng lượng khác.',
            tags: ['absorb', 'dark_power', 'energy_drain'],
        },
        martial: {
            id: 'am_da_chi_da',
            name: 'Ám Dạ Chi Dạ',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'am',
            desc: 'Thân pháp như ma quỷ, biến mất trong bóng tối để ra đòn đánh lén chí mạng hoặc đâm sau lưng.',
            tags: ['stealth', 'backstab', 'crit'],
        },
        divine: {
            id: 'tu_than_chi_nhan',
            name: 'Tử Thần Chi Nhãn',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'am',
            desc: 'Đôi mắt đen tuyền, bất kỳ ai bị nhìn thấy đều rơi vào trạng thái ảo giác và mất phương hướng.',
            tags: ['illusion', 'fear', 'confuse'],
        },
    },
    {
        element: 'loi',
        name: 'Lôi',
        cultivation: {
            id: 'cuu_thien_ung_loi_kinh',
            name: 'Cửu Thiên Ứng Lôi Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'loi',
            desc: 'Mượn tia sét thiên địa rèn luyện kinh mạch, nguyên lực có tính chấn động mãnh liệt.',
            tags: ['shock', 'paralyze', 'burst'],
        },
        martial: {
            id: 'loi_dinh_nhat_kich',
            name: 'Lôi Đình Nhất Kích',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'loi',
            desc: 'Một chiêu tốc độ cực nhanh, mũi đấm hoặc mũi kiếm được bao phủ bởi sấm sét, gây tê liệt và bỏng điện.',
            tags: ['burst', 'paralyze', 'fast_strike'],
        },
        divine: {
            id: 'thien_loi_pha',
            name: 'Thiên Lôi Phá',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'loi',
            desc: 'Triệu hồi trận sét từ trên trời giáng xuống khu vực chỉ định, xóa sổ vạn vật.',
            tags: ['aoe', 'lightning_storm', 'burst'],
        },
    },
    {
        element: 'phong',
        name: 'Phong',
        cultivation: {
            id: 'con_bang_bien_hoa_kinh',
            name: 'Côn Bằng Biến Hóa Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'phong',
            desc: 'Nguyên lực nhẹ nhàng, không có trọng lượng, giúp cơ thể bay lượn và di chuyển cực nhanh.',
            tags: ['speed', 'evasion', 'flight'],
        },
        martial: {
            id: 'thien_phong_doat_menh',
            name: 'Thiên Phong Đoạt Mệnh',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'phong',
            desc: 'Một chiêu kiếm vô hình, không nghe tiếng, chỉ cảm thấy gió thổi qua rồi địch đã đứt cổ.',
            tags: ['speed', 'silent_kill', 'slash'],
        },
        divine: {
            id: 'phong_bao_chi_nhan',
            name: 'Phong Bạo Chi Nhãn',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'phong',
            desc: 'Tạo ra một cơn lốc xoáy thu nhỏ, hút mọi đòn tấn công nguyên lực vào bên trong và đẩy ngược trở lại.',
            tags: ['reflect', 'absorb', 'storm'],
        },
    },
    {
        element: 'bang',
        name: 'Băng',
        cultivation: {
            id: 'van_nien_huyen_bang_chan_kinh',
            name: 'Vạn Niên Huyền Băng Chân Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'bang',
            desc: 'Hàn khí tràn vào tứ chi bách hài, khiến cơ thể có nhiệt độ cực thấp.',
            tags: ['cold', 'freeze_resist', 'slow'],
        },
        martial: {
            id: 'bang_phach_chuong',
            name: 'Băng Phách Chưởng',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'bang',
            desc: 'Chưởng lực mang hàn băng, trúng đòn sẽ khiến máu đông cứng, thân thể tê liệt.',
            tags: ['freeze', 'paralyze', 'cold_damage'],
        },
        divine: {
            id: 'tuyet_doi_lanh_do',
            name: 'Tuyệt Đối Lãnh Độ',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'bang',
            desc: 'Đóng băng thời không trong một phạm vi nhỏ, khiến mọi chuyển động của địch đều bị khựng lại.',
            tags: ['time_freeze', 'area_disable', 'cold'],
        },
    },
    {
        element: 'doc',
        name: 'Độc',
        cultivation: {
            id: 'van_doc_bat_than_kinh',
            name: 'Vạn Độc Bất Thân Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'doc',
            desc: 'Luyện thể trở nên miễn dịch với mọi loại độc, đồng thời nội nguyên biến thành độc tố.',
            tags: ['poison_immunity', 'poison_power', 'dot'],
        },
        martial: {
            id: 'hoa_cot_mien_chuong',
            name: 'Hóa Cốt Miên Chưởng',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'doc',
            desc: 'Chưởng pháp không gây sát thương vật lý mà ngấm độc vào người, khiến xương địch mềm nhũn và tan rã.',
            tags: ['poison', 'armor_melt', 'dot'],
        },
        divine: {
            id: 'doc_chuong_son_lam',
            name: 'Độc Chướng Sơn Lâm',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'doc',
            desc: 'Phát tán khói độc màu tím bao trùm cả một vùng, vừa tàng hình vừa gây độc cho kẻ địch xâm nhập.',
            tags: ['aoe', 'poison_cloud', 'stealth'],
        },
    },
    {
        element: 'long',
        name: 'Long',
        cultivation: {
            id: 'ngu_trao_hoang_long_kinh',
            name: 'Ngũ Trảo Hoàng Long Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'long',
            desc: 'Hấp thụ linh khí long mạch, gia tăng khí huyết, có uy áp của Chân Long.',
            tags: ['hp', 'dragon_aura', 'bloodline'],
        },
        martial: {
            id: 'long_trao_thien_ha',
            name: 'Long Trảo Thiên Hạ',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'long',
            desc: 'Một trảo chụp xuống như rồng há mồm, xé nát phòng ngự, bóp nát đầu địch.',
            tags: ['crush', 'armor_break', 'dragon_claw'],
        },
        divine: {
            id: 'long_uy_linh_vuc',
            name: 'Long Uy Lĩnh Vực',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'long',
            desc: 'Phát ra uy áp dòng máu rồng, khiến địch yếu hơn run sợ, không dám cử động.',
            tags: ['domain', 'fear', 'suppression'],
        },
    },
    {
        element: 'phat',
        name: 'Phật',
        cultivation: {
            id: 'kim_cuong_bat_hoai_the_kinh',
            name: 'Kim Cương Bất Hoại Thể Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'phat',
            desc: 'Luyện da thịt thành kim cương, phòng thủ tuyệt đối, trấn áp tà ma.',
            tags: ['defense', 'anti_demon', 'cleanse'],
        },
        martial: {
            id: 'nhu_lai_than_chuong',
            name: 'Như Lai Thần Chưởng',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'phat',
            desc: 'Một chưởng từ trên cao đánh xuống, quang mang chói lọi, không chạm vào thân mà đánh vào tâm thức địch, khiến chúng bỏ chạy tán loạn.',
            tags: ['mind_attack', 'fear', 'holy_damage'],
        },
        divine: {
            id: 'phat_quang_pho_chieu',
            name: 'Phật Quang Phổ Chiếu',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'phat',
            desc: 'Ánh sáng vàng tỏa ra, giải trừ mọi hiệu ứng khống chế và chữa lành cho đồng minh trong phạm vi.',
            tags: ['cleanse', 'heal', 'support'],
        },
    },
    {
        element: 'ma',
        name: 'Ma',
        cultivation: {
            id: 'thien_ma_huyet_kinh',
            name: 'Thiên Ma Huyết Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'ma',
            desc: 'Lấy máu làm nguyên lực, càng đánh càng mạnh, càng bị thương càng điên cuồng.',
            tags: ['berserk', 'lifesteal', 'blood_power'],
        },
        martial: {
            id: 'ma_van_chi_trao',
            name: 'Ma Vẫn Chi Trảo',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'ma',
            desc: 'Quyền pháp tà ác, mỗi đòn đánh đều hút sinh khí của địch để hồi phục cho bản thân.',
            tags: ['lifesteal', 'melee', 'demon_claw'],
        },
        divine: {
            id: 'huyet_sac_thien_dia',
            name: 'Huyết Sắc Thiên Địa',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'ma',
            desc: 'Biến cả chiến trường thành màu máu, khiến địch bị hút máu, suy yếu liên tục và giảm tốc độ.',
            tags: ['domain', 'lifesteal', 'slow', 'weaken'],
        },
    },
    {
        element: 'thoi_gian',
        name: 'Thời Gian',
        cultivation: {
            id: 'tue_nguyet_tan_kinh',
            name: 'Tuế Nguyệt Tàn Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'thoi_gian',
            desc: 'Chấp nhận đánh đổi tuổi thọ để đổi lấy sức mạnh tức thời hoặc làm chậm thời gian cục bộ.',
            tags: ['time', 'sacrifice', 'haste', 'slow'],
        },
        martial: {
            id: 'thoi_quang_tram',
            name: 'Thời Quang Trảm',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'thoi_gian',
            desc: 'Một nhát chém vào hiện tại, vết thương trúng sẽ già đi trong tức khắc, khiến vết thương không thể lành.',
            tags: ['anti_heal', 'time_slash', 'wound'],
        },
        divine: {
            id: 'hoi_tuc_luan_hoi',
            name: 'Hồi Túc Luân Hồi',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'thoi_gian',
            desc: 'Đưa một vật hoặc bản thân quay ngược thời gian về trạng thái khỏe mạnh ban đầu.',
            tags: ['rewind', 'restore', 'time'],
        },
    },
    {
        element: 'khong_gian',
        name: 'Không Gian',
        cultivation: {
            id: 'hu_vo_chan_kinh',
            name: 'Hư Vô Chân Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'khong_gian',
            desc: 'Nội lực không nằm trong cơ thể mà nằm trong kẽ không gian, có thể triệu hồi bất ngờ.',
            tags: ['space', 'hidden_power', 'surprise_attack'],
        },
        martial: {
            id: 'son_ha_tan_pha',
            name: 'Sơn Hà Tẫn Phá',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'khong_gian',
            desc: 'Một chưởng đánh ra không chạm thân mà làm gãy xương địch nhờ sức ép không gian, tạo ra vết rạn nứt.',
            tags: ['space_pressure', 'armor_break', 'remote_hit'],
        },
        divine: {
            id: 'thuan_di',
            name: 'Thuấn Di',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'khong_gian',
            desc: 'Lập tức dịch chuyển bản thân hoặc một vật nặng trong phạm vi tới bất kỳ vị trí nào khác.',
            tags: ['teleport', 'space', 'mobility'],
        },
    },
    {
        element: 'tu_vong',
        name: 'Tử Vong',
        cultivation: {
            id: 'tu_than_chi_hap',
            name: 'Tử Thần Chi Hấp',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'tu_vong',
            desc: 'Thi triển công pháp sẽ liên tục rút mạng sống của người xung quanh để nuôi dưỡng nguyên lực đen tối.',
            tags: ['death', 'life_drain', 'dark_power'],
        },
        martial: {
            id: 'doat_hon_trao',
            name: 'Đoạt Hồn Trảo',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'tu_vong',
            desc: 'Một trảo bóp vào cổ họng đối phương, trực tiếp bóp nát linh hồn, không để lại vết thương ngoài da.',
            tags: ['soul_damage', 'death', 'execute'],
        },
        divine: {
            id: 'tu_lenh',
            name: 'Tử Lệnh',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'tu_vong',
            desc: 'Ra lệnh cho một kẻ địch yếu hơn ngã xuống ngay lập tức, bỏ qua phòng thủ.',
            tags: ['execute', 'death_order', 'ignore_defense'],
        },
    },
    {
        element: 'sinh_menh',
        name: 'Sinh Mệnh',
        cultivation: {
            id: 'tao_hoa_lam_dien_kinh',
            name: 'Tạo Hóa Lam Điền Kinh',
            type: 'cultivation',
            equipType: 'passive',
            requiredSpiritRoot: 'sinh_menh',
            desc: 'Nguyên lực mang đầy hạt ánh sáng xanh, chữa lành mọi tế bào bị tổn thương.',
            tags: ['heal', 'life_force', 'regen'],
        },
        martial: {
            id: 'hoi_xuan_chi_thu',
            name: 'Hồi Xuân Chi Thủ',
            type: 'martial',
            equipType: 'active',
            requiredSpiritRoot: 'sinh_menh',
            desc: 'Vỗ nhẹ lên người đồng đội, vết thương lập tức khép miệng, như đưa mùa xuân về.',
            tags: ['heal', 'support', 'single_target'],
        },
        divine: {
            id: 'bat_tu_chi_dia',
            name: 'Bất Tử Chi Địa',
            type: 'divine',
            equipType: 'ultimate',
            requiredSpiritRoot: 'sinh_menh',
            desc: 'Tạo ra một vòng tròn sáng trên mặt đất, bất kỳ sinh vật nào đứng trong đó đều có tốc độ hồi phục tăng gấp trăm lần.',
            tags: ['domain', 'mass_regen', 'support'],
        },
    },
];

module.exports = ELEMENT_SKILL_SETS;
