module.exports = [
  // 20 Phàm Duyên
  { id: 'lao_ong_cau_ca', tier: 'PHAM', name: 'Lão Ông Câu Cá', description: 'Một lão ông áo tơi ngồi câu cá bên hồ tĩnh lặng.', choices: [{ id: 'hanh_le', text: 'Tiến lên hành lễ' }, { id: 'hoi_dao', text: 'Hỏi thăm đạo lý' }, { id: 'bo_qua', text: 'Lặng lẽ rời đi' }] },
  { id: 'thuong_nhan_ky_la', tier: 'PHAM', name: 'Thương Nhân Kỳ Lạ', description: 'Một thương nhân gánh hòm gỗ cũ mời ngươi chọn một món.', choices: [{ id: 'mua_re', text: 'Mua món rẻ nhất' }, { id: 'mac_ca', text: 'Mặc cả' }, { id: 'khong_mua', text: 'Không mua gì' }] },
  { id: 'ngoc_gian_cu', tier: 'PHAM', name: 'Ngọc Giản Cũ', description: 'Trong bụi cỏ có một mảnh ngọc giản phủ bụi.', choices: [{ id: 'doc_ngay', text: 'Đọc ngay tại chỗ' }, { id: 'cat_di', text: 'Cất vào túi' }, { id: 'dap_vo', text: 'Đập vỡ thử xem' }] },
  { id: 'thi_the_tu_si', tier: 'PHAM', name: 'Thi Thể Tu Sĩ', description: 'Một thi thể tu sĩ nằm cạnh vách đá, túi trữ vật đã rách.', choices: [{ id: 'luc_soat', text: 'Lục soát cẩn thận' }, { id: 'chons_cat', text: 'Chôn cất tử tế' }, { id: 'roi_di', text: 'Rời đi' }] },
  { id: 'son_dong_bo_hoang', tier: 'PHAM', name: 'Sơn Động Bỏ Hoang', description: 'Một sơn động tối om tỏa ra linh khí mỏng manh.', choices: [{ id: 'tien_vao', text: 'Tiến vào thăm dò' }, { id: 'nem_da', text: 'Ném đá dò đường' }, { id: 'bo_qua', text: 'Bỏ qua' }] },
  { id: 'tieng_chuong_dem', tier: 'PHAM', name: 'Tiếng Chuông Đêm', description: 'Giữa đêm vang lên tiếng chuông xa lạ.', choices: [{ id: 'lan_nghe', text: 'Lắng nghe' }, { id: 'lan_theo', text: 'Lần theo âm thanh' }, { id: 'bit_tai', text: 'Bịt tai tu luyện' }] },
  { id: 'dong_suoi_linh_khi', tier: 'PHAM', name: 'Dòng Suối Linh Khí', description: 'Một dòng suối nhỏ có linh khí nhè nhẹ bốc lên.', choices: [{ id: 'uong_nuoc', text: 'Uống một ngụm' }, { id: 'tam_rua', text: 'Tắm rửa kinh mạch' }, { id: 'lay_nuoc', text: 'Lấy nước mang đi' }] },
  { id: 'con_cao_trang', tier: 'PHAM', name: 'Con Cáo Trắng', description: 'Một con cáo trắng bị mắc bẫy, đôi mắt rất có linh tính.', choices: [{ id: 'cuu_no', text: 'Cứu nó' }, { id: 'quan_sat', text: 'Quan sát thêm' }, { id: 'bo_di', text: 'Bỏ đi' }] },
  { id: 'cay_kho_no_hoa', tier: 'PHAM', name: 'Cây Khô Nở Hoa', description: 'Một gốc cây khô bỗng nở ra đóa hoa nhạt màu.', choices: [{ id: 'hai_hoa', text: 'Hái hoa' }, { id: 'tuoi_nuoc', text: 'Tưới linh thủy' }, { id: 'ngoi_thien', text: 'Ngồi thiền bên cạnh' }] },
  { id: 'tui_vai_vo_chu', tier: 'PHAM', name: 'Túi Vải Vô Chủ', description: 'Một túi vải cũ nằm bên đường, không rõ chủ nhân.', choices: [{ id: 'mo_ra', text: 'Mở ra' }, { id: 'rao_tim_chu', text: 'Rao tìm chủ nhân' }, { id: 'da_ra_xa', text: 'Đá ra xa' }] },
  { id: 'tieu_dao_si', tier: 'PHAM', name: 'Tiểu Đạo Sĩ Lạc Đường', description: 'Một tiểu đạo sĩ hỏi đường về đạo quán.', choices: [{ id: 'chi_duong', text: 'Chỉ đường' }, { id: 'dua_di', text: 'Dẫn đi một đoạn' }, { id: 'treu_choc', text: 'Trêu chọc vài câu' }] },
  { id: 'vien_da_am', tier: 'PHAM', name: 'Viên Đá Ấm', description: 'Một viên đá ven đường tỏa hơi ấm kỳ lạ.', choices: [{ id: 'cam_len', text: 'Cầm lên xem' }, { id: 'truyen_khi', text: 'Truyền linh khí vào' }, { id: 'nem_di', text: 'Ném đi' }] },
  { id: 'bong_nguoi_duoi_trang', tier: 'PHAM', name: 'Bóng Người Dưới Trăng', description: 'Dưới ánh trăng có bóng người luyện kiếm.', choices: [{ id: 'hoc_len', text: 'Lén học kiếm thế' }, { id: 'len_tieng', text: 'Lên tiếng chào hỏi' }, { id: 'rut_lui', text: 'Rút lui' }] },
  { id: 'lu_huong_vo_danh', tier: 'PHAM', name: 'Lư Hương Vô Danh', description: 'Một lư hương nhỏ còn vương tàn hương.', choices: [{ id: 'thap_huong', text: 'Thắp thêm hương' }, { id: 'lay_di', text: 'Mang đi' }, { id: 'cui_lay', text: 'Cúi lạy ba lần' }] },
  { id: 'dan_lo_vo_chu', tier: 'PHAM', name: 'Đan Lô Vô Chủ', description: 'Một đan lô nứt vỡ bị bỏ lại sau bụi trúc.', choices: [{ id: 'kiem_tra', text: 'Kiểm tra đan lô' }, { id: 'nhom_lua', text: 'Nhóm lửa thử luyện' }, { id: 'bo_qua', text: 'Bỏ qua' }] },
  { id: 'manh_ban_do_rach', tier: 'PHAM', name: 'Mảnh Bản Đồ Rách', description: 'Một mảnh bản đồ rách chỉ còn vài ký hiệu mơ hồ.', choices: [{ id: 'doc_ky', text: 'Đọc kỹ ký hiệu' }, { id: 'cat_giu', text: 'Cất giữ' }, { id: 'dot_di', text: 'Đốt đi' }] },
  { id: 'con_duong_re', tier: 'PHAM', name: 'Con Đường Rẽ', description: 'Trước mặt có một lối rẽ chưa từng xuất hiện.', choices: [{ id: 'di_vao', text: 'Đi vào' }, { id: 'danh_dau', text: 'Đánh dấu rồi quay lại' }, { id: 'khong_di', text: 'Không đi' }] },
  { id: 'hat_giong_la', tier: 'PHAM', name: 'Hạt Giống Lạ', description: 'Một hạt giống màu xanh ngọc nằm trong khe đá.', choices: [{ id: 'gieo_ngay', text: 'Gieo ngay' }, { id: 'cat_giu', text: 'Cất giữ' }, { id: 'nghien_cuu', text: 'Nghiên cứu' }] },
  { id: 'nguoi_hat_rong', tier: 'PHAM', name: 'Người Hát Rong', description: 'Một người hát rong kể chuyện tiên nhân dưới chợ nhỏ.', choices: [{ id: 'thuong_tien', text: 'Thưởng linh thạch' }, { id: 'lang_nghe', text: 'Lắng nghe' }, { id: 'bo_di', text: 'Bỏ đi' }] },
  { id: 'giac_mong_ngan', tier: 'PHAM', name: 'Giấc Mộng Ngắn', description: 'Ngươi chợp mắt và thấy một giấc mộng rất thật.', choices: [{ id: 'tinh_lai_nho', text: 'Cố ghi nhớ' }, { id: 'chim_sau', text: 'Chìm sâu vào mộng' }, { id: 'tinh_day', text: 'Lập tức tỉnh dậy' }] },

  // 10 Linh Duyên
  { id: 'linh_ho_hoa_hinh', tier: 'LINH', name: 'Linh Hồ Hóa Hình', description: 'Một linh hồ sắp hóa hình bị lôi quang quấy nhiễu.', choices: [{ id: 'ho_phap', text: 'Hộ pháp cho nó' }, { id: 'rut_lui', text: 'Rút lui quan sát' }, { id: 'lay_long', text: 'Thu lấy linh lông' }] },
  { id: 'kiem_khach_cut_tay', tier: 'LINH', name: 'Kiếm Khách Cụt Tay', description: 'Một kiếm khách cụt tay xin ngươi cùng luận kiếm.', choices: [{ id: 'luan_kiem', text: 'Luận kiếm' }, { id: 'ty_thi', text: 'Tỷ thí một chiêu' }, { id: 'tu_choi', text: 'Từ chối' }] },
  { id: 'dan_su_lang_thang', tier: 'LINH', name: 'Đan Sư Lang Thang', description: 'Một đan sư tóc bạc mời ngươi thử một viên đan mới.', choices: [{ id: 'thu_dan', text: 'Thử đan' }, { id: 'xin_cong_thuc', text: 'Xin công thức' }, { id: 'mua_dan', text: 'Mua đan' }] },
  { id: 'am_duong_tinh_thach', tier: 'LINH', name: 'Âm Dương Tinh Thạch', description: 'Hai viên tinh thạch đen trắng xoay quanh nhau.', choices: [{ id: 'lay_den', text: 'Lấy viên đen' }, { id: 'lay_trang', text: 'Lấy viên trắng' }, { id: 'dung_hop', text: 'Thử dung hợp' }] },
  { id: 'mieng_bi_canh_vo', tier: 'LINH', name: 'Miệng Bí Cảnh Vỡ', description: 'Một khe không gian nứt ra, bên trong thấp thoáng bảo quang.', choices: [{ id: 'tien_vao', text: 'Tiến vào' }, { id: 'tham_do', text: 'Thăm dò từ xa' }, { id: 'phong_an', text: 'Phong ấn khe nứt' }] },
  { id: 'co_thu_biet_noi', tier: 'LINH', name: 'Cổ Thụ Biết Nói', description: 'Một cổ thụ gọi tên đạo hiệu của ngươi.', choices: [{ id: 'dap_lai', text: 'Đáp lời' }, { id: 'hoi_duyen', text: 'Hỏi về cơ duyên' }, { id: 'chem_vo', text: 'Chém thử vỏ cây' }] },
  { id: 'thanh_kiem_gi_set', tier: 'LINH', name: 'Thanh Kiếm Gỉ Sét', description: 'Một thanh kiếm gỉ cắm sâu trong đá.', choices: [{ id: 'rut_kiem', text: 'Rút kiếm' }, { id: 'truyen_khi', text: 'Truyền linh khí' }, { id: 'cui_chao', text: 'Cúi chào kiếm linh' }] },
  { id: 'tang_thu_cac_bo_hoang', tier: 'LINH', name: 'Tàng Thư Các Bỏ Hoang', description: 'Một tàng thư các nhỏ xuất hiện sau màn sương.', choices: [{ id: 'doc_sach', text: 'Đọc sách' }, { id: 'lay_sach', text: 'Lấy một quyển' }, { id: 'dot_den', text: 'Đốt đèn tìm lối' }] },
  { id: 'bach_lien_trong_mua', tier: 'LINH', name: 'Bạch Liên Trong Mưa', description: 'Một đóa bạch liên nở giữa cơn mưa linh khí.', choices: [{ id: 'hai_lien', text: 'Hái bạch liên' }, { id: 'bao_ve', text: 'Bảo vệ đến khi tàn mưa' }, { id: 'ngoi_thien', text: 'Ngồi thiền bên hoa' }] },
  { id: 'tieng_go_cua_dem', tier: 'LINH', name: 'Tiếng Gõ Cửa Đêm', description: 'Nửa đêm có tiếng gõ cửa ba lần, ngoài cửa không thấy ai.', choices: [{ id: 'mo_cua', text: 'Mở cửa' }, { id: 'hoi_ai', text: 'Hỏi là ai' }, { id: 'mac_ke', text: 'Mặc kệ' }] },

  // 5 Huyền Duyên
  { id: 'tan_hon_dai_nang', tier: 'HUYEN', name: 'Tàn Hồn Đại Năng', description: 'Một tàn hồn cổ xưa tỉnh dậy trong ngọc bội.', choices: [{ id: 'lang_nghe', text: 'Lắng nghe truyền đạo' }, { id: 'trao_doi', text: 'Trao đổi điều kiện' }, { id: 'phong_an', text: 'Phong ấn tàn hồn' }] },
  { id: 'tien_phu_do_nat', tier: 'HUYEN', name: 'Tiên Phủ Đổ Nát', description: 'Một tiên phủ đổ nát trồi lên khỏi lòng đất.', choices: [{ id: 'vao_chinh_dien', text: 'Vào chính điện' }, { id: 'tim_kho', text: 'Tìm bảo khố' }, { id: 'lay_gach', text: 'Thu vài mảnh tiên thạch' }] },
  { id: 'than_thu_ngan_nam', tier: 'HUYEN', name: 'Thần Thụ Ngàn Năm', description: 'Một thần thụ tỏa ánh sáng xanh, lá rụng như mưa.', choices: [{ id: 'nhat_la', text: 'Nhặt lá thần thụ' }, { id: 'khac_ten', text: 'Khắc tên lên vỏ cây' }, { id: 'ngo_dao', text: 'Ngồi ngộ đạo' }] },
  { id: 'long_mach_thuc_tinh', tier: 'HUYEN', name: 'Long Mạch Thức Tỉnh', description: 'Long mạch dưới chân chợt thức tỉnh, đại địa rung chuyển.', choices: [{ id: 'hap_thu', text: 'Hấp thu long khí' }, { id: 'tran_an', text: 'Trấn an long mạch' }, { id: 'dao_len', text: 'Đào xuống tìm nguồn' }] },
  { id: 'mat_na_vo_danh', tier: 'HUYEN', name: 'Mặt Nạ Vô Danh', description: 'Một chiếc mặt nạ không mặt nằm trong hộp đồng.', choices: [{ id: 'deo_len', text: 'Đeo lên' }, { id: 'nhin_lau', text: 'Nhìn thật lâu' }, { id: 'cat_niem_phong', text: 'Cất và niêm phong' }] },

  // 1 Thiên Mệnh
  { id: 'thien_thu_giang_the', tier: 'THIEN_MENH', name: 'Thiên Thư Giáng Thế', description: 'Trời đất đổi màu, một trang thiên thư rơi xuống trước mặt ngươi.', choices: [{ id: 'doc_thien_thu', text: 'Đọc Thiên Thư' }, { id: 'te_bai', text: 'Tế bái thiên địa' }, { id: 'niem_phong', text: 'Niêm phong chờ thời' }] }
];
