(function(){
  const $id=id=>document.getElementById(id);
  const state={name:'',token:'',questions:[],index:0,answers:[]};
  async function request(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||'Thiên cơ không phản hồi.');return d;}
  function showQuestion(){const q=state.questions[state.index];if(!q)return; $id('destiny-progress-text').textContent=`${state.index+1} / ${state.questions.length}`;$id('destiny-progress-bar').style.width=`${state.index/state.questions.length*100}%`;$id('destiny-question').textContent=q.text;$id('destiny-answers').innerHTML=q.answers.map(a=>`<button class="destiny-answer" data-answer="${a.id}">${a.text}</button>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>choose(b.dataset.answer));}
  async function choose(answerId){const q=state.questions[state.index];state.answers.push({questionId:q.id,answerId});state.index++;if(state.index<state.questions.length){showQuestion();return;}try{$id('destiny-message').textContent='Thiên mệnh đang định hình...';const data=await request('/api/player',{method:'POST',body:JSON.stringify({name:state.name,assessmentToken:state.token,answers:state.answers})});$id('destiny-assessment').classList.add('hidden');window.dispatchEvent(new CustomEvent('thienmenh:created',{detail:data}));}catch(e){$id('destiny-message').textContent=e.message;}}
  async function begin(name){state.name=String(name||'').trim();if(state.name.length<2)throw new Error('Đạo hiệu phải có ít nhất 2 ký tự.');const data=await request('/api/player/assessment');const a=data.assessment||data;state.token=a.token||a.assessmentToken;state.questions=a.questions||[];state.index=0;state.answers=[];if(!state.token||!state.questions.length)throw new Error('Không tải được Thiên Mệnh Khảo Nghiệm.');$id('destiny-assessment').classList.remove('hidden');$id('destiny-message').textContent='';showQuestion();}
  function gradeName(level){const n=Number(level||1);if(n>=401)return`Thiên phẩm · ${n-400}/100`;if(n>=301)return`Địa phẩm · ${n-300}/100`;if(n>=201)return`Huyền phẩm · ${n-200}/100`;if(n>=101)return`Hoàng phẩm · ${n-100}/100`;return`Phàm phẩm · ${n}/100`;}
  function render(player,roots){if(!player)return;const list=Array.isArray(roots)?roots:[];const root=list.find(x=>String(x.id)===String(player.spiritual_root||player.spiritualRoot));const name=player.spiritual_root_name||player.spiritualRootName||root?.name||'Chưa ngộ Linh Căn';const level=player.spiritual_root_level||player.spiritualRootLevel||1;const special=Boolean(player.is_innate_special_root||player.isInnateSpecialRoot);const set=(id,v)=>{const e=$id(id);if(e)e.textContent=v};set('root-full-name',name);set('root-full-description',player.spiritual_root_description||root?.description||'Chưa có ghi chép.');set('root-grade-level',gradeName(level));set('root-element-name',root?.element||'—');set('root-rarity',root?.rarity||'—');set('root-origin',special?'Thiên sinh đặc tính':'Thiên Mệnh Ngũ Hành');set('root-type-badge',root?.rootType==='dao_tac'?'Đạo Tắc':root?.rootType==='dac_tinh'?'Linh Căn Đặc Tính':'Ngũ Hành');const growth=player.spiritual_root_growth||{hp:root?.growthHp,mp:root?.growthMp,attack:root?.growthAttack,defense:root?.growthDefense};const box=$id('root-growth-list');if(box)box.innerHTML=[['Sinh Lực',growth.hp],['Nội Lực',growth.mp],['Công Kích',growth.attack],['Phòng Thủ',growth.defense]].map(([n,v])=>`<span>${n} ×${Number(v||1).toFixed(2)}</span>`).join('');}
  window.ThienMenhUI={begin,render,gradeName};
})();
